server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://mysql-dev:3308/rmdb
    username: root
    password: password
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect